/*
 * This source file was generated by the Gradle 'init' task
 */
package dev.ultreon.pythonc;

import java.io.File;
import java.io.IOException;

public class App {
    public String compile(String pythonFile) throws IOException {
        new PythonCompiler().compile(new File(pythonFile));
        return "Compiled " + pythonFile;
    }

    public static void main(String[] args) throws IOException {
        if (args.length == 0) {
//            System.out.println("Usage: java -jar pythonifier.jar <python file>");
//            System.exit(1);
            PythonCompiler compiler = new PythonCompiler();
            compiler.compile("""
                    from net.fabricmc.api import ModInitializer
                    from pythonvm.api import implements
                    
                    @implements(ModInitializer)
                    class ExampleMod:
                        def onInitialize(self):
                            print("Hello, world!")
                    
                    def main():
                        print("Hey there!", 42)
                    """, "example/hello.py");

            compiler.pack("example");
            return;
        }
        System.out.println(new App().compile(args[0]));
    }
}
