/*
 * This source file was generated by the Gradle 'init' task
 */
package dev.ultreon.pythonc;

import java.io.File;
import java.io.IOException;
import java.lang.management.ManagementFactory;
import java.util.ArrayList;
import java.util.List;

public class App {
    public static void main(String[] args) throws IOException {
        String outputJar = null;
        String jarFile = ManagementFactory.getRuntimeMXBean().getName().split("@")[0];
        if (jarFile == null) {
            jarFile = "<filename>.jar";
        }

        List<String> sources = new ArrayList<>();
        for (int i = 0, argsLength = args.length; i < argsLength; i++) {
            String arg = args[i];
            if (arg.equals("-o")) {
                outputJar = args[i + 1];
                i++;
                continue;
            }

            if (arg.startsWith("-")) {
                System.err.println("Unknown argument: " + arg);
                System.exit(1);
            }

            sources.add(arg);
        }

        if (outputJar == null) {
            System.err.println("Usage: java -jar " + jarFile + " -o <output jar> <python file> ...");
            System.exit(1);
        }

        if (sources.isEmpty()) {
            System.err.println("Usage: java -jar " + jarFile + " -o <output jar> <python file> ...");
            System.exit(1);
        }

        String outputDir = "build/tmp/compilePython";
        PythonCompiler pythonCompiler = new PythonCompiler();
        for (String source : sources) {
            if (!new File(source).exists()) {
                System.err.println("Source directory does not exist: " + source);
                System.exit(1);
            }
        }
        for (String source : sources) {
            pythonCompiler.compileSources(source);
        }
        pythonCompiler.pack(outputDir, outputJar);
    }
}
